definitions:
  models.Event:
    properties:
      contact:
        type: string
      day:
        type: integer
      free:
        type: integer
      id:
        type: integer
      imgURL:
        type: string
      month:
        type: integer
      nickname:
        type: string
      tages:
        items:
          $ref: '#/definitions/models.Tag'
        type: array
      time:
        type: integer
      title:
        type: string
      year:
        type: integer
    type: object
  models.Tag:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  requests.Event:
    properties:
      contact:
        type: string
      day:
        type: integer
      free:
        type: integer
      id:
        type: integer
      imgURL:
        type: string
      month:
        type: integer
      nickname:
        type: string
      time:
        type: integer
      title:
        type: string
      year:
        type: integer
    type: object
  requests.Login:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  requests.RegisterUser:
    properties:
      email:
        type: string
      level:
        type: integer
      nickname:
        type: string
      password:
        type: string
    type: object
  responses.Event:
    properties:
      contact:
        type: string
      day:
        type: integer
      free:
        type: integer
      id:
        type: integer
      imgURL:
        type: string
      month:
        type: integer
      nickname:
        type: string
      tages:
        items:
          $ref: '#/definitions/responses.Tag'
        type: array
      time:
        type: integer
      title:
        type: string
      year:
        type: integer
    type: object
  responses.Message:
    properties:
      message:
        type: string
    type: object
  responses.Tag:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  responses.Users:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      nickname:
        type: string
      password:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
  description: Dev Event API
  license: {}
  title: Dev Event Server
paths:
  /admin/events:
    post:
      description: 새 이벤트 생성
      parameters:
      - description: create event
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.Event'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.Message'
        "400": {}
        "401": {}
        "500": {}
      security:
      - userAPIKey: []
      tags:
      - Admin - Events
  /admin/events/:eventID:
    delete:
      description: 이벤트 삭제
      parameters:
      - description: eventID
        in: path
        name: eventID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Message'
        "401": {}
        "404": {}
        "500": {}
      security:
      - userAPIKey: []
      tags:
      - Admin - Events
    get:
      description: 이벤트 정보 조회
      parameters:
      - description: eventID
        in: path
        name: eventID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "401": {}
        "404": {}
        "500": {}
      security:
      - userAPIKey: []
      tags:
      - Admin - Events
    put:
      description: 이벤트 수정
      parameters:
      - description: Save event
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.Event'
      - description: eventID
        in: path
        name: eventID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Event'
        "401": {}
        "404": {}
        "500": {}
      security:
      - userAPIKey: []
      tags:
      - Admin - Events
  /admin/tags:
    delete:
      description: 태그 삭제
      parameters:
      - description: tagID
        in: path
        name: tagID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.Message'
            type: array
        "400": {}
        "401": {}
        "500": {}
      security:
      - userAPIKey: []
      tags:
      - Admin - Tags
    get:
      description: 모든 태그 조회
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.Tag'
            type: array
        "400": {}
        "401": {}
        "500": {}
      security:
      - userAPIKey: []
      tags:
      - Admin - Tags
    post:
      description: 태그 생성
      parameters:
      - description: tagID
        in: path
        name: tagID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Message'
        "401": {}
        "404": {}
        "500": {}
      security:
      - userAPIKey: []
      tags:
      - Admin - Tags
  /admin/tags/:tagID:
    put:
      description: 태그 수정
      parameters:
      - description: tagID
        in: path
        name: tagID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Message'
        "401": {}
        "404": {}
        "500": {}
      security:
      - userAPIKey: []
      tags:
      - Admin - Tags
  /admin/users:
    get:
      description: Get all users info
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.Users'
            type: array
        "401": {}
        "404": {}
        "500": {}
      security:
      - userAPIKey: []
      tags:
      - Admin - Users
  /admin/users/:userID:
    delete:
      description: 회원 정보 삭제
      parameters:
      - description: userID
        in: path
        name: userID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Message'
        "401": {}
        "404": {}
        "500": {}
      security:
      - userAPIKey: []
      tags:
      - Admin - Users
    get:
      description: 회원 정보 조회
      parameters:
      - description: userID
        in: path
        name: userID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Users'
        "401": {}
        "404": {}
        "500": {}
      security:
      - userAPIKey: []
      tags:
      - Admin - Users
    put:
      description: 회원 정보 수정
      parameters:
      - description: userID
        in: path
        name: userID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Users'
        "400": {}
        "401": {}
        "404": {}
        "500": {}
      security:
      - userAPIKey: []
      tags:
      - Admin - Users
  /auth/login:
    post:
      description: 로그인
      parameters:
      - description: 로그인
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.Login'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/requests.Login'
        "401": {}
        "500": {}
      tags:
      - Auth
  /auth/register:
    post:
      description: 회원가입
      parameters:
      - description: register user
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.RegisterUser'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responses.Message'
        "400": {}
        "500": {}
      tags:
      - Auth
  /events/:year/:month:
    get:
      description: 이벤트 가져오기 (년, 월)
      parameters:
      - description: year
        in: path
        name: year
        required: true
        type: string
      - description: month
        in: path
        name: month
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.Event'
            type: array
        "401": {}
        "404": {}
        "500": {}
      tags:
      - Events
  /users:
    get:
      description: 나의 프로필 확인
      parameters:
      - description: email
        in: path
        name: email
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Users'
        "401": {}
        "500": {}
      security:
      - userAPIKey: []
      tags:
      - Users
    put:
      description: 프로필 수정
      parameters:
      - description: email
        in: path
        name: email
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Message'
        "401": {}
        "404": {}
        "500": {}
      security:
      - userAPIKey: []
      tags:
      - Users
swagger: "2.0"
